### ISSUE TITLE
10.6+ Support

### ISSUE THREAD

**Issue by truealphamc** [yellows8/3ds_homemenuhax#113]
Have you found a workaround with the new update?
And if so, are you working on it?

**Comment by yellows8** [comment]
https://github.com/yellows8?tab=activity https://3dbrew.org/wiki/Special:RecentChanges

**Comment by PreamWolfe** [comment]
any updates on a timeframe? you've worked so hard on this and it must be so frustrating to see nintendo patch it up every damn time. i just want any approximate timeframe so i can be prepared

**Comment by yellows8** [comment]
Still more interested in other things atm hence the previous comment...

Still don't have any useful vuln(s) for old3ds-browserhax yet either. https://github.com/yellows8/3ds_browserhax_common/issues/28

**Comment by PreamWolfe** [comment]
sorry again for the pestering, but was wondering if you knew of any way other than homebrew to extract/decrypy ds save files?
just as a workaround while i try out the webkit for you

**Comment by yellows8** [comment]
You mean raw 3DS gamecard saveimages?

**Comment by PreamWolfe** [comment]
just the save file, for use with programs on the pc via SD card

sorry for the late reply by the way

**Comment by yellows8** [comment]
Besides JPN cyber-gadget, Powersaves doesn't support arbitrary savefile modifying last time I checked.

**Comment by PreamWolfe** [comment]
imma delete all my messages once we've finished this convo so i don't clog up this thread, i can't seem to contact you any other way
i have save files saved onto my sd card for my 2ds with the newest update. now i'm not technically inclined in any way, shape, or form, all i want to do is transfer the save file via my sd to a form where it can be edited using a file i downloaded online. i donated to the creator of the file because i hate not supporting people's hard work
is there any way i can transfer the save file from my sd to a usable format without using homebrew where i can edit it on my pc?

**Comment by yellows8** [comment]
Gamecard or eShop titles?

**Comment by PreamWolfe** [comment]
eShop

**Comment by yellows8** [comment]
Then no.

**Comment by NathanDreamweaver** [comment]
there is the r4 save dongle

**Comment by Gliscor** [comment]
So, browser/menuhax support for 10.6, 10.7, and 11.0 is highly unlikely.

**Comment by yellows8** [comment]
"highly unlikely" Never said that.
