### ISSUE TITLE
 Smash for 3DS crash when suspending software (OLD 3DS)

### ISSUE THREAD

**Issue by armaanaki** [yellows8/3ds_homemenuhax#13]
If you are playing Smash on the Old 3DS with homemenuhax installed, then decide to suspend the game using the home button, the DS will freeze and you are forced to do a hard reset.

**Comment by yellows8** [comment]
*3DS

I don't think there's any way to fix this: with apps which require different APPMEMTYPE value(s), the Home Menu linearmem heap is located elsewhere. This results in the themehax triggering a data abort due to unmapped memory being accessed. And obviously the heap addresses in themehax can't be changed without breaking it for hard-boot, so....

**Comment by yellows8** [comment]
d69f9f4b62484b2c19334b36f9b222127bcb794b
