### ISSUE TITLE
SaveData.dat invalid filesize, with error 0xfffffffe.

### ISSUE THREAD

**Issue by Kygdom** [yellows8/3ds_homemenuhax#131]
When i try to install Menuhax, just after the line "Loading SaveData.dat" i have the following message : "The SaveData.dat filesize is invalid. This may mean you're running menuhax_manager on an unsupported system version", with the error code being "0xfffffffe".

My system-version is Old3DS 11.0.0-33 EUR. I took the most recent homebrew starter kit and unziped menuhax 3.0. I have no idea what i could have done wrong.

Btw, browserhax works very well.

**Comment by Unknownstarz93** [comment]
Got exactly same 3ds and same problem as you. 
Browser hax works but cant install menuhax

**Comment by Tanooks** [comment]
I'm having the same issue with N3DS 11.0.0-33 USA.

**Comment by yellows8** [comment]
Upload/whatever the log like menuhax_manager displayed @ error.

**Comment by Tanooks** [comment]
I will do that immediately, @yellows8!

**Comment by Tanooks** [comment]
Here it is, @yellows8. 
<img width="661" alt="screen shot 2016-07-28 at 12 37 58 am" src="https://cloud.githubusercontent.com/assets/20693890/17201343/93290aba-545b-11e6-95bd-f4a30746f112.png">

**Comment by yellows8** [comment]
I've always thought Home Menu would convert old-format SaveData.dat into the current format and save it, but apparently not. :(

For now you can just delete/rename the main Home Menu extdata as mentioned in the README(and of course backup that directory first).

**Comment by Tanooks** [comment]
@yellows8, ah, I see...er...how would I do that and where would I find it?

**Comment by yellows8** [comment]
Did you all ever downgrade or tinker with NAND-titles at some point?(That old SaveData.dat format-version should never be used on New3DS AFAIK...)

**Comment by yellows8** [comment]
@Tanooks README

**Comment by luoyianwu** [comment]
@yellows8 
![ss](https://cloud.githubusercontent.com/assets/15962892/17202043/428c72a4-54c9-11e6-8e74-179bd71f8b4c.png)
I renamed one of the extdata folders, and this happened.

**Comment by loadstarnes** [comment]
Hey @yellows8 , I think my experience is worth mentioning:  
I was having identical problems to the posters above, I did what you said (renaming the extdata directory) . Initially, I was still thrown an error and a failed installation when I tried to install menuhax, but I did some tinkering around and **if you delete or rename the extdata directory you should also open the themes menu and let it give you the little "setting up" blurb before trying to install menuhax**.  
If I had known this, it would have saved me 3-4 tedius browserhax runs!  

And of course, THANK YOU @yellows8   

Edit: I was running with a vanilla 11.0.0-33U o3DS console, if that matters!

**Comment by luoyianwu** [comment]
@The-Fizz
Your solution worked! Good job.

**Comment by Tanooks** [comment]
@The-Fizz, your solution worked with flying colors! Thank you so much, and of course, thank you, @yellows8!

**Comment by yellows8** [comment]
:)

**Comment by loadstarnes** [comment]
Made an account just to post that, glad it was worth it!

**Comment by Unknownstarz93** [comment]
Sorry guys, im abit nooby here. What do i rename the extdata

**Comment by bir-d** [comment]
very confused, i have old format save data as i found out, ive read the readme multiple times, and still cant figure out how to get to new savedata from an old format :C sorry, im a noob.

**Comment by Xyphoseos** [comment]
I have the same error I don't understand what that do I have to make?
(sorry for my bad english)

**Comment by Dharengo** [comment]
Use https://www.3dbrew.org/wiki/Extdata to find and delete the home menu extdata for your 3DS version on your SD card. Then launch your 3DS, which will be forced to re-initialize the extdata. It should install MenuHax now.

**Comment by bir-d** [comment]
alright, i know where it is. now how do i delete it? the tool on the page 404'd :C

EDIT: using 11.0.0-33E if that helps
EDIT2: nothing on sd card either

**Comment by Unknownstarz93** [comment]
Finally did it,
Simple Guidance:

SD CARD> Nintendo 3DS > ed1c90edf9986d74c071237ef93a89d6 > 523400ab4760ac8d534430320002544d then you'd see extdata folder. 
Delete or rename it.
After doing so click on the theme on top left (in menu) and let it set up.
Now you can install it,

**Comment by yellows8** [comment]
"then you'd see extdata folder. " <- You're supposed to delete/rename "extdata/{extdataID-low for Home Menu}/"

**Comment by Kygdom** [comment]
So i renamed the extdata folder and i was able to install menuhax. Thanks for the help.

Now i have other issues but i don't think that's the place to talk about them so i'm going to open another issue thing.

**Comment by SamusAranX** [comment]
What's the harm in renaming the extdata folder instead of the folder inside of the extdata folder?
I renamed the extdata folder, let the menu regenerate all necessary files, then successfully installed menuhax, with no obvious damage to the system.

**Comment by Dharengo** [comment]
I do not think it does any harm. What matters are the actual files at the end of the path.

**Comment by Xyphoseos** [comment]
Thanks for all 😁😁😁

**Comment by yellows8** [comment]
@SamusAranX Because that's _all_ extdata.

**Comment by SamusAranX** [comment]
@yellows8 This is probably not the place for an extended chat, but could you give me a short explanation on what extdata is? I haven't been able to find a good, non-technical explanation so far.

**Comment by Dharengo** [comment]
From what I understand, (correct me if I'm wrong) extdata as a whole is just information for the OS that is not stored in the system itself, but on the SD card. This seems to include all the metadata for whatever game is installed on the SD card, as well as theme data. The extdata that's being used for the exploit seems to be the extdata for the home menu itself, where info on its theme and layout is stored.

**Comment by NathanDreamweaver** [comment]
@SamusAranX extdata is EXTraDATA that isn't stored in the NAND

**Comment by ghost** [comment]
Well, although my game backups all simultaneously broke (small loss, I think. Maybe.), the *hax seems to have installed.

**Comment by Luis0MLG** [comment]
damn erasing it actually works. thanks guys :smiley:

**Comment by Migg003** [comment]
hello umm... for me there are two folders with the extdata... one, being with other folders and another being all by itself. which do I delete?? because I am having the same problem. And also the folders aren't called the same as Unknownstarz93 commented, is that normal?

Thanks, -Mig

**Comment by Airpoizon** [comment]
So I did all this and it worked, but all of my downloaded games appeared in the present icon you get when you first download it. Does this mean all my data is lost or something?

**Comment by yellows8** [comment]
This extdata is where the present-status is stored... Uninstall, then unwrap them before installing menuhax.

**Comment by exorx** [comment]
Hmm, I've got multiple extData folders...I don't know which one to choose, here's what my Nintendo 3DS folder looks like:

```
/Nintendo 3DS
    /xxxxxxxxxxxxxxxxxxxxxx
          /aaaaaaaaaaaaaaaaaaaaa
             /extdata
                     /00000000
    /yyyyyyyyyyyyyyyyyyyyyy
        /bbbbbbbbbbbbbbbbbb
             /dbs
             /extdata
                     /00000000
             /Nintendo DSIWare
             /title
    /zzzzzzzzzzzzzzzzzzzzzz
    /ccccccccccccccccccccc
             /extdata
                     /00000000
    /Private
```

I may have multiple folders because I changed 3DS a couple of times so I always transferred my data from the old to the new one...

Am I gonna loose anything if I delete the extdata folder?  I've got a couple of downloaded games I don't want to loose.

I also have a custom Theme right now, am I gonna be able to use it with MenuHax or do I need to use one of the default themes?

Thanks

Btw, I've got a New 3DS.

**Comment by cobr4a** [comment]
I delete extdata and the install option on menuhax setup work well. I set de d-pad down to call entry point ok. But when i reboot the system with the d-pad down pressed the top screen show a picture as a TV without antena and follow the message to call big N assistence. If I reboot without d-pad down the system reboot to home menu normally. My entry point not working or I need go to step 2 and install downgrade files to sd card to work the entry point? Thanks!

**Comment by yellows8** [comment]
Post the log.

**Comment by cobr4a** [comment]
where is the log location on sd card?

**Comment by cobr4a** [comment]
menuhax_manager v3.0 by yellows8.
Deleting SD data from old menuhax_manager versions, etc...
Opening extdata archives...
Finished opening extdata.

Downloading config via HTTPC...
Parsing config...
menuhax_manager v3.0 by yellows8.

This can install Home Menu haxx to the SD card, for booting the *hax payloads. Select an option with the below menu via the D-Pad/Circle-Pad, then press A. You can press the B button to exit. You can press the Y button at any time while at a menu like the below one, to toggle the screen being used by this app.
The theme menu options are only available when the cfg file exists on SD with an exploit installed which requires seperate theme-data files.

-> Install
   Delete
   Configure menuhax.
   Configure the menuhax splash-screen.
Getting system info...
Detected system-version: New3DS 10.7.0-32 USA

Skip ropbin-payload setup? Normally you should just press B.
A = Yes, B = No.

Skipping ropbin payload setup. If this was not intended, re-run the install again after this.
Copying stage2 to SD...
Src path = 'romfs:/finaloutput/menuhax_payload.zip@menuhax_USA25600_new3ds.bin', dst = 'sdmc:/menuhax/stage2/menuhax_USA25600_new3ds.bin'.
Reading stage2...
Writing stage2...
Installing sdiconhax...
Loading SaveData.dat...
Locating data in Home Menu linearmem heap...
Failed to find the buffer for the target objects-list.
Error from sdiconhax_locatelinearmem(): 0xfffffffc
Trying to load addrs from the built-in list since auto-locate failed...
Running SD setup for stage1...
Loading exploit file-data + writing into extdata...
Install finished successfully.

Press the A button to continue.
menuhax_manager v3.0 by yellows8.
Installed menuhax from the last installation run:
'v3.0:sdiconhax'

This can install Home Menu haxx to the SD card, for booting the *hax payloads. Select an option with the below menu via the D-Pad/Circle-Pad, then press A. You can press the B button to exit. You can press the Y button at any time while at a menu like the below one, to toggle the screen being used by this app.
The theme menu options are only available when the cfg file exists on SD with an exploit installed which requires seperate theme-data files.

-> Install
   Delete
   Configure menuhax.
   Configure the menuhax splash-screen.
menuhax_manager v3.0 by yellows8.
Installed menuhax from the last installation run:
'v3.0:sdiconhax'

This can install Home Menu haxx to the SD card, for booting the *hax payloads. Select an option with the below menu via the D-Pad/Circle-Pad, then press A. You can press the B button to exit. You can press the Y button at any time while at a menu like the below one, to toggle the screen being used by this app.
The theme menu options are only available when the cfg file exists on SD with an exploit installed which requires seperate theme-data files.

   Install
-> Delete
   Configure menuhax.
   Configure the menuhax splash-screen.
menuhax_manager v3.0 by yellows8.
Installed menuhax from the last installation run:
'v3.0:sdiconhax'

This can install Home Menu haxx to the SD card, for booting the *hax payloads. Select an option with the below menu via the D-Pad/Circle-Pad, then press A. You can press the B button to exit. You can press the Y button at any time while at a menu like the below one, to toggle the screen being used by this app.
The theme menu options are only available when the cfg file exists on SD with an exploit installed which requires seperate theme-data files.

   Install
   Delete
-> Configure menuhax.
   Configure the menuhax splash-screen.
Configuring the padcfg file on SD...
The cfg file already exists on SD.
Current cfg:
Type 0x0: None, the default PAD trigger is used.
Current delay value: 3000000000(3.000000 seconds).
The menuhax thread is currently disabled, use the PAD option for it to enable it.
When both the menuhax-thread and Home Menu are active, it will essentially check the specified PAD-value every <delayvalue>, on match it will trigger running the *hax payload.

Press the A button to continue.
Select an option with the below menu. You can press B to exit without changing anything..

-> Type1: Only trigger the haxx when the PAD state matches the specified value(specified button(s) must be pressed).
   Type2: Only trigger the haxx when the PAD state doesn't match the specified value.
   Type0: Default PAD config is used.
   Configure the delay value used with the delay right before jumping to the *hax payload. This may affect the random *hax payload boot failures.
   Configure the delay value used with the menuhax thread.
   Configure the PAD value for the menuhax thread.

Press the button(s) you want to select for the PAD state value as described above(no New3DS-only buttons). If you want to select <no-buttons>, don't press any buttons. Then, while the buttons are being pressed, if any, touch the bottom-screen.
Selected PAD value: 0x80 D-PAD DOWN 
Config file successfully written.
Configuration finished successfully.

Press the A button to continue.
menuhax_manager v3.0 by yellows8.
Installed menuhax from the last installation run:
'v3.0:sdiconhax'

This can install Home Menu haxx to the SD card, for booting the *hax payloads. Select an option with the below menu via the D-Pad/Circle-Pad, then press A. You can press the B button to exit. You can press the Y button at any time while at a menu like the below one, to toggle the screen being used by this app.
The theme menu options are only available when the cfg file exists on SD with an exploit installed which requires seperate theme-data files.

   Install
   Delete
-> Configure menuhax.
   Configure the menuhax splash-screen.

Press the START button to exit.

**Comment by yellows8** [comment]
"My entry point not working "
"Skip ropbin-payload setup? Normally you should just press B.
A = Yes, B = No.

Skipping ropbin payload setup. If this was not intended, re-run the install again after this."

.............................................................................................

**Comment by cobr4a** [comment]
I skip ? I´ll try again sorry.

**Comment by cobr4a** [comment]
Tks yellows8 working now!

**Comment by yellows8** [comment]
:)

**Comment by cobr4a** [comment]
on step 2 all files ok.. downgrade is ok without error. When console restart black screen. I turn on without sd card, home menu is up, on put back sd card the console hangs (freeze). Any advice yellow8?

**Comment by cobr4a** [comment]
I am embassor console..

**Comment by yellows8** [comment]
Well obviously you shouldn't have menuhax installed for a Home Menu version that's different from what's actually installed, but this isn't the place for downgrade help either.

**Comment by cobr4a** [comment]
Sure, you help again. Sorry for posting in this section of forum. ;-)

**Comment by yellows8** [comment]
Leaving this open until next release I guess.

**Comment by exorx** [comment]
Hi again, any idea on my multiple exdata folders?

Thanks

**Comment by batman5241** [comment]
@Unknownstarz93 oh my gosh thanks it worked thanks dude the only thing is i wish i did that earlier cause i booted with browser hacks like 50 times

**Comment by conornolan123** [comment]
@yellows8 im having a problem related to this, im running 11.0-33u on my 3ds, but it says "The SaveData.dat filesize is invalid. This may mean your running menuhax_manager on an unsupported system-version
Install failed:   0xfffffffe.

**Comment by korjal** [comment]
you dont have to lose your save you could just replace the files after you installed the homebrew

**Comment by RagingIceSprite** [comment]
Trying to homebrew my 3ds and I am having the same issue. However, when I rename the extdata folder, my monster hunter generations save data gets deleted off of the SD card. Is there any way that I can replace the contents of the extdata folder so I can keep my save data after I install menuhax?

**Comment by yellows8** [comment]
You're not supposed to rename the 'extdata' directory, only the one for Home Menu mentioned above.

**Comment by Poncus** [comment]
Can someone tell me how to install the hax? , i've readed this: https://github.com/yellows8/3ds_homemenuhax/blob/master/README.md
and i didn't found a installation tutorial.

**Comment by SoraHjort** [comment]
[See Edit2 at bottom]

I'm having this issue as well. Deleting the directories and making sure the theme data is recreated by the 3DS's theme manager, isn't fixing it for me.

Hardware: Old 3DS
Ver: 11.0.0-33 USA
Method of accessing homebrew: BrowserHax

Same error log as everyone else is giving.

edit: added the method of getting to the homebrew incase that is relevant.

Edit2: Seems I was going at the wrong folder. Thought it was a similar problem I had last year, so I was deleting/renaming that folder instead of the correct one.

**Comment by Zerofoxgiven** [comment]
I deleted my full extdata folder on accident... what will happen now??? The homebrew launcher CIA doesn't work anymore, it crashes at the yellow screen :(
EDIT: Nevermind, menuhax now fully installed, thanks guys!

**Comment by Zerofoxgiven** [comment]
Menuhax gives me a black screen after I installed it though. Had to remove the SD card and change the theme.

**Comment by yellows8** [comment]
@Zerofoxgiven "The homebrew launcher CIA " Why are you using menuhax then?

"change the theme." This issue is only for sdiconhax.....

**Comment by Kerasu** [comment]
For those asking what to rename the extdata file to, you can name it anything you want. I literally just renamed mine "rename" and it installed fine after that.

**Comment by Kerasu** [comment]
@yellows8 Ok so I got this to work, but now when I go to my Mii Plaza all the games I've played had the data erased? How do I fix this?
I kept a backup and everything on my computer.

**Comment by Kerasu** [comment]
Derp nevermind I fixed it. It had to do with the files "0000008f" and  "000002cd".
I had to keep the new ones made in the new extdata file for those and then transfer all my stuff from my original extdata file to the new one without replacing those 2.

**Comment by yellows8** [comment]
I specifically said to _only_ touch the _Home Menu_ extdata.....

**Comment by Kerasu** [comment]
Ahh whoops. Yeah I just saw that. I have a weird way of figuring things out I guess.. Sorry about that.

**Comment by ben43210** [comment]
Ive tried everything above and nothing works for me. im still receiving the same error and i dont get how this is working for everybody else but not me. please help

**Comment by ben43210** [comment]
Can someone please help me solve this issue. Ive even got a new SD card to see if memory was the problem but it STILL work work! i have tried everything above and still cant get it to work. I tried this on my brothers SD card in his 3DS XL and it worked with no issues at all... please help

**Comment by DailyPopcorn** [comment]
Guys please help me i can't understand those steps. Please helpo me step by step in installing menuhax v3.1 please. btw i'm using  New3DS 11.0.0 33 US if this will help

**Comment by pzppo** [comment]
Okay I know this is an old thread but im still getting the same error ( 0xfffffffe ) when I go to install it and I am on system version 11.2.0-35 U and I am using menuhax version 3.1 I tried deleting the extdata file but I cant even go to install on menuhax and the same thing happens to me if I rename the extdata if anyone sees this i would love some help :)

**Comment by yellows8** [comment]
This is completely unrelated, read the actual displayed message & README ......

**Comment by Rocket411** [comment]
ok, having the same error code and issue as all these guys, do I rename the exdata file itself, or do I just rename the file when you open it??

**Comment by Rocket411** [comment]
So I renamed the exdata file, then I went and put the sd card in my ds and fired up homebrew. i clicked the  menuhax_manager v3.2 and this popped up:

menuhax_manager v3.2 by yellows8.
Deleting SD data from old menuhax_manager versions, etc...
Opening extdata archives...
Failed to open theme extdata with extdataID=0x000002cd, retval: 0xc8804464
Exit this app, then goto Home Menu theme-settings so that Home Menu can create the theme extdata.

An error occured. If this is an actual issue not related to user failure, please report this to here if it persists(or comment on an already existing issue if needed), with the file from SD 'menuhax_manager.log'(normally located at '/3ds/menuhax_manager/' unless the app is running from elsewhere): https://github.com/yellows8/3ds_homemenuhax/issues
Press the START button to exit.

**Comment by Rocket411** [comment]
also, my error code is:

menuhax_manager v3.2 by yellows8.
Deleting SD data from old menuhax_manager versions, etc...
Opening extdata archives...
Finished opening extdata.

Downloading config via HTTPC...
Parsing config...
menuhax_manager v3.2 by yellows8.

This can install Home Menu haxx to the SD card, for booting the *hax payloads. Select an option with the below menu via the D-Pad/Circle-Pad, then press A. You can press the B button to exit. You can press the Y button at any time while at a menu like the below one, to toggle the screen being used by this app.
The theme menu options are only available when the cfg file exists on SD with an exploit installed which requires seperate theme-data files.

-> Install
   Delete
   Configure menuhax.
   Configure the menuhax splash-screen.
Have you fully read the latest README?
https://github.com/yellows8/3ds_homemenuhax
A = Yes, B = No.

Getting system info...
Detected system-version: New3DS 11.2.0-35 USA

Skip updating the *hax payload? Normally you should just press B.
A = Yes, B = No.

Setting up *hax payload...
Requesting the actual payload URL with HTTPC...
Downloading the actual payload with HTTPC...
Writing the menuropbin to SD...
ropbin_filepath = sdmc:/menuhax/ropbin/ropbinpayload_menuhax_USA26624_new3ds.bin
Copying stage2 to SD...
Src path = 'romfs:/finaloutput/menuhax_payload.zip@menuhax_USA26624_new3ds.bin', dst = 'sdmc:/menuhax/stage2/menuhax_USA26624_new3ds.bin'.
Reading stage2...
Writing stage2...
Installing bossbannerhax...
Is >=v1.2 ctr-httpwn active(with the included bosshaxx active), or "CFW" running / sigchecks patched on the running system? If not, bossbannerhax can't be installed.
A = Yes, B = No.

Copying stage1 to SD...
Src path = 'romfs:/finaloutput/stage1_bossbannerhax.zip@menuhax_USA26624_new3ds.bin', dst = 'sdmc:/menuhax/stage1/menuhax_USA26624_new3ds.bin'.
Reading stage1...
Writing stage1...
cur_programid=0x0004001020021d00, extdataID=0x0000021d.
Running extdata recreation if required, for the currently running title...
FSUSER_GetFormatInfo: numdirs = 0x0000000a, numfiles = 0x0000000a.
Extdata recreation for the current title isn't needed.
Running BOSS setup...
Waiting for the task to finish running...
...
bossGetTaskState: status=0x2.
...
bossGetTaskState: status=0x7.
BOSS task failed. This usually indicates a network failure.
bossReinit() with menu programID(0x0004003000008f02) returned: 0x00000000.
Install failed: 0xfffffff7.

An error occured. If this is an actual issue not related to user failure, please report this to here if it persists(or comment on an already existing issue if needed), with the file from SD 'menuhax_manager.log'(normally located at '/3ds/menuhax_manager/' unless the app is running from elsewhere): https://github.com/yellows8/3ds_homemenuhax/issues
Press the START button to exit.

**Comment by Rocket411** [comment]
also, do I need luma cwf if I already have homebrew?

**Comment by loadstarnes** [comment]
I'm too tired to read the whole thing but you should rename the extdata FOLDER (aka Directory). All this is doing is tricking the DS into thinking it doesn't have the extdata setup yet, so it creates it again...

**Comment by Rocket411** [comment]
ok, thank you

**Comment by yellows8** [comment]
That has *absolutely* *nothing* to do with this issue.
