### ISSUE TITLE
Compile for only one firmware version?

### ISSUE THREAD

**Issue by RuinTD** [yellows8/3ds_homemenuhax#15]
Trying to compile all the firmware versions with a custom theme has taken 9 hours so far. Is there any way to compile homemenuhax for only MY firmware version?

**Comment by yellows8** [comment]
On my machine building with the custom theme I used, it took 60x longer for each build(~1minute instead of ~1s).

I guess you could figure out the required command from this: https://github.com/yellows8/3ds_homemenuhax/blob/master/Makefile#L122

EDIT: If you don't want to wait for an easier solution later, that is. #12

**Comment by RuinTD** [comment]
Oh. Thanks...
EDIT: It JUST finished compiling. XD
