### ISSUE TITLE
Home Menu Theme Bug (Icon / Folder)

### ISSUE THREAD

**Issue by uintdev** [yellows8/3ds_homemenuhax#3]
With Homemenuhax installed, go to the normal home menu, open any folder (or create and then open  one), shutdown the 3DS and then turn it back on.
Once that's done, you should be able to see that the smaller blocks that are supposed to be behind the icons are solid grey and has no radius set (completely square). Closing the folder will for a second show all of the icons missing in the home menu and then it would go back to normal (normal blocks, icons appear, functions normally).
This does happen every time so it should be pretty simple to replicate.

Before the installation, I had set the theme to 'default'.
Installer used was v1.2.

I know that the whole point of this is to have access to HB menu and to have it to do its job, so I wouldn't consider this one to be so important.

**Comment by yellows8** [comment]
It's probably not possible to fix that, but it's really not much of an issue since it goes back to normal quickly @ folder closing.

**Comment by yellows8** [comment]
The actual official default theme has the same affect except for the gray gfx(EDIT2: not sure if "same affect" was really accurate with v1.2).

EDIT:
Changing the TARGETOVERWRITE_MEMCHUNKADR value in the Makefile results in the gray issue no longer triggering. With that restored, jumping back to the main Home Menu code immediately after PREPARE_RET2MENUCODE results in the gray isue triggering. So the issue somehow happens due to overwriting this r4 value on stack.

**Comment by yellows8** [comment]
@CoolApps45 What system-version are you on?

On newer system-versions it seems to be fixed with my local changes, but it's still broken with v9.2. :-(

**Comment by uintdev** [comment]
Currently 10.1.0-27E.
I wish I could be on v9.2, a lot of things you can mess around with.

**Comment by yellows8** [comment]
Ugh... s/"fixed"/"theme-cache not used anymore"(?). :-/

**Comment by yellows8** [comment]
288d30b40967ff36e05c371d86b387025b0d7813
