### ISSUE TITLE
BlargSNES freeze

### ISSUE THREAD

**Issue by DillPo313** [yellows8/3ds_homemenuhax#6]
This also effects Browserhax. BlargSNES works fine in other exploits. When you start it and try to load a ROM it freezes. Everything else I've tried works fine.

**Comment by yellows8** [comment]
I'm aware of this, been trying to figure out how to properly fix it for a while.

All homebrew apps which run threads on core1 are broken, this includes: BlargSNES, 3dscraft, and portal3DS.

This fails basically because no official app was ever launched the normal way with APT: http://3dbrew.org/wiki/APT:SetApplicationCpuTimeLimit

With browserhax for now, one can just launch an official app, exit it, then run browserhax. From there apps which use core1 threads will work fine. That manual method obviously won't work for themehax.

**Comment by DillPo313** [comment]
Do you think it can be fixed?

**Comment by smealum** [comment]
haven't tested this myself but i think you might be able to get those
working under themehax this way :
1. launch official game/app
2. press power button
3. hold L
4. press home button

hopefully that should run hblauncher fine

obviously that's not ideal but it's something

**Comment by DillPo313** [comment]
Thanks Smea! That totally works! :)

**Comment by yellows8** [comment]
This should get properly fixed via a hblauncher-payload update eventually, hopefully.

**Comment by smealum** [comment]
yeah i'm working on it, hopefully should be a real fix in a few days

**Comment by Pingu879** [comment]
Hey will this ever be fixed ? <3

**Comment by smealum** [comment]
the fix will be shipped with *hax 2.5, which should come relatively soon.
not much left to do but i'm very busy atm so no clear ETA yet.

**Comment by rams32d5** [comment]
Hey smealum quick question... see I was using themehax to launch it I hold L after turning the console on but for some reason it won't launch anymore any other way to launch it that you may know of?
