### ISSUE TITLE
Error code: 0xc8804470

### ISSUE THREAD

**Issue by GurElad2001** [yellows8/3ds_homemenuhax#71]
![20160108_170731](https://cloud.githubusercontent.com/assets/16611668/12201040/b8e264ec-b62a-11e5-80a0-d4fa0479d1ab.jpg)
hello! it gives me this screen when i trying to download menuhax! what should i do?

**Comment by yellows8** [comment]
Try using the "Delete" option in the app.

**Comment by GurElad2001** [comment]
It gives me "deletion failed: 0xc8804470"

**Comment by MightyJAK** [comment]
I got the same errors. It seemed installation was partially successful, as when I checked my themes my favorite themes had been cleared from theme shuffle. I selected the basic black theme an ran the installer again, this time it looked to be a complete success, even though there was still an Error 0xc8804470 in the log.
![wp_20160121_001](https://cloud.githubusercontent.com/assets/16828750/12500291/5352fa2c-c077-11e5-8653-8d94b45c152d.jpg)

**Comment by MightyJAK** [comment]
Turns out it wasn't a complete success. Rebooting while holding L brought up the menuhax loader splash screen, but it froze with a yellow bottom screen. To make sure it wasn't a fluke, I rebooted 3 more times, each time got the same result. I uninstalled with the Delete option again (no errors this time) and tried to reinstall one more time. This time the Error 0xc8804470 message scrolled past multiple times, but it finally finished with the "Install finished successfully" again. Now it boots properly into the homebrew launcher when I hold L while powering on, I guess 3rd time's the charm?
