### ISSUE TITLE
Menuhax stops working when screenshots_raw.bin gets too big (around 4MB)

### ISSUE THREAD

**Issue by corky1983** [yellows8/3ds_homemenuhax#89]
I have a N3DS with 9.9FW, and have installed the latest version of Menuhax.  Everything works great, however it seems that if the screenshots_raw.bin file gets too big (over 4MB or around there), Menuhax stops working.  If I replace the screenshots_raw.bin with an old version, or delete it, Menuhax starts working again.

A workaround seems to be to not take screenshots, but even if you power down the 3DS from within Homebrew Browser, it seems to append data to screenshots_raw.bin.  Then after a while, the file gets too large, and it stops Menuhax from working.

**Comment by yellows8** [comment]
Please be more specific with "not working".

**Comment by corky1983** [comment]
When I hold down the 'L' button, and boot, it just goes to the standard 3DS home menu.  I took a diff of my SD card both before and after it stops working, and the only file change is screenshots_raw.bin.  I am not entirely sure if its the file size of this file that causes it to stop working, but I can tell you that deleting it fixes the issue for a while.

**Comment by yellows8** [comment]
That makes no sense, screenshots_raw.bin wouldn't even be used by anything with what you're describing.

It's more likely that you're having SD FAT-FS issues.

**Comment by corky1983** [comment]
I will do more testing and let you know.

**Comment by bigbeau** [comment]
I can confirm, this is true. When my screenshots_raw.bin got too big (6MB for me), menuhax simply stopped loading when I pressed L at startup. Deleting the file fixed the issue, and now menuhax loads again. 

So its true that the screenshots_raw.bin file is whats messing things up, maybe there is some way around this ~~(not that its too big of a deal, since you can just delete it again from within CTRXplorer or another 3ds file viewer)~~ (Actually, I am an idiot, you can't launch CTRXplorer without the HB menu... so actually it may be kind of a big deal, heh)

btw I'm using the New 3ds XL and my firmware is 10.5-30U

**Comment by yellows8** [comment]
My screenshots_raw.bin is ~46MB and menuhax still loads fine. If you all are still having issues, you can re-open this if formatting your SD FS didn't help.
